import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GridBackgroundDemo } from "@/components/re-use/grid-back";
import { Spotlight } from "@/components/ui/Spotlight";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio ",
  description: "Generated by create next app",
  icons: null,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Spotlight
          className="top-20 left-0 md:left-0 md:-top-20"
          fill="white"
        />

        {children}
        <GridBackgroundDemo />
      </body>
    </html>
  );
}
